"""fb

Revision ID: 0844c85671d9
Revises: 
Create Date: 2017-09-05 21:42:15.234396+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0844c85671d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('fb_post_id', sa.String(length=92), nullable=True))
    op.add_column('donations', sa.Column('fb_publish_attempts', sa.Integer(), nullable=False))
    op.add_column('donations', sa.Column('fb_publish_last_attempt_at', sa.DateTime(), nullable=True))
    op.add_column('donations', sa.Column('fb_published_at', sa.DateTime(), nullable=True))
    op.add_column('donations', sa.Column('fb_skip_msg', sa.SmallInteger(), nullable=False))
    op.create_index(op.f('ix_donations_fb_skip_msg'), 'donations', ['fb_skip_msg'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_fb_skip_msg'), table_name='donations')
    op.drop_column('donations', 'fb_skip_msg')
    op.drop_column('donations', 'fb_published_at')
    op.drop_column('donations', 'fb_publish_last_attempt_at')
    op.drop_column('donations', 'fb_publish_attempts')
    op.drop_column('donations', 'fb_post_id')
    # ### end Alembic commands ###
